### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by vlimmere** [danielkupco/viewX-vscode#5]
After following the install procedure, this is the message that appears in the VSCODE log (Extension Host):
[2020-04-24 17:52:47.990] [exthost] [info] eager extensions activated
[2020-04-24 17:53:16.251] [exthost] [error] Activating extension textX.textX failed due to an error:
[2020-04-24 17:53:16.251] [exthost] [error] TypeError: Cannot read property 'onReady' of undefined
	at c:\Users\berna\.vscode\extensions\textx.textx-0.1.2\dist\extension.js:1:99773
	at Generator.throw (<anonymous>)
	at a (c:\Users\berna\.vscode\extensions\textx.textx-0.1.2\dist\extension.js:1:98840)

Any suggestion on what to do next?

**Comment by danielkupco** [comment]
Hi @vlimmere ,
By looking at the logs, it seems to me that they are related to another vscode extension for [textX](https://github.com/textX/textX-LS) which is not maintained by me. Try opening an issue on that repository.

However, your message made me realize that this extension is not working anymore as well, as it has been neglected by me for quite some time now. I will do my best to update it and make it functional again in the following days.

Thanks and good luck.
